## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

<font color='#ff0000'>HINT的語意感覺好像test_size可以做到對不同結果切割合併，但我查了一下應該沒有這種功能。</font>  
~中文真難~

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X[:40], y[:40], test_size=10, random_state=42)
X2_train, X2_test, y2_train, y2_test = train_test_split(X[41:], y[41:], test_size=10, random_state=42)
X_test = np.vstack([X1_test, X2_test])
y_test = np.hstack([y1_test, y2_test])
print('X_test :', X_test, sep="\n")
print('-'*30)
print('y_test :', y_test, sep='\n')

X_test :
[[ 95  96  97  98  99]
 [ 80  81  82  83  84]
 [ 75  76  77  78  79]
 [130 131 132 133 134]
 [ 20  21  22  23  24]
 [ 60  61  62  63  64]
 [185 186 187 188 189]
 [135 136 137 138 139]
 [195 196 197 198 199]
 [ 30  31  32  33  34]
 [595 596 597 598 599]
 [980 981 982 983 984]
 [845 846 847 848 849]
 [480 481 482 483 484]
 [675 676 677 678 679]
 [350 351 352 353 354]
 [940 941 942 943 944]
 [460 461 462 463 464]
 [695 696 697 698 699]
 [910 911 912 913 914]]
------------------------------
y_test :
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
